environment:
  name: Production
  identifier: production
  orgIdentifier: scottishtecharmy
  projectIdentifier: oyci-quarkus
  description: "Production environment for OYCI Quarkus API"
  type: Production
  tags:
    env: production
  variables:
    - name: namespace
      type: String
      value: oyci-prod
    - name: valuesFile
      type: String
      value: helm/oyci-quarkus/values-prod.yaml

