quarkus.datasource.db-kind=h2
quarkus.datasource.jdbc.url=jdbc:h2:mem:events;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
quarkus.datasource.username=sa
quarkus.datasource.password=sa

# CORS
cors.allowed-origin=http://localhost:5173

# Scheduling rules
scheduling.required-staff-per-event=2

# Logging
quarkus.log.level=INFO
quarkus.log.console.enable=true
quarkus.log.console.format=%d{HH:mm:ss} %-5p [%c{2.}] %s%e%n
quarkus.http.access-log.enabled=true
quarkus.http.access-log.pattern="%r" %s (%D ms)
quarkus.log.category."org.scottishtecharmy".level=DEBUG

