package org.scottishtecharmy.oyci.quarkus.service;

import jakarta.enterprise.context.ApplicationScoped;
import jakarta.inject.Inject;
import jakarta.transaction.Transactional;
import org.jboss.logging.Logger;
import org.mindrot.jbcrypt.BCrypt;
import org.scottishtecharmy.oyci.quarkus.dto.CreateStaffRequest;
import org.scottishtecharmy.oyci.quarkus.dto.UpdateStaffRequest;
import org.scottishtecharmy.oyci.quarkus.exception.BusinessValidationException;
import org.scottishtecharmy.oyci.quarkus.exception.ResourceNotFoundException;
import org.scottishtecharmy.oyci.quarkus.model.*;
import org.scottishtecharmy.oyci.quarkus.repository.*;
import org.scottishtecharmy.oyci.quarkus.response.StaffDetailResponse;

@ApplicationScoped
public class StaffService {

    private static final Logger LOG = Logger.getLogger(StaffService.class);

    @Inject
    StaffRepository staffRepository;

    @Inject
    UserRepository userRepository;

    @Inject
    StaffTypeRepository staffTypeRepository;

    @Inject
    QualificationRepository qualificationRepository;

    @Inject
    RoleRepository roleRepository;

    @Inject
    ContactDetailRepository contactDetailRepository;

    /**
     * Get a single staff member by ID
     */
    public StaffDetailResponse getStaffById(Long staffId) {
        LOG.infof("Fetching staff with ID: %d", staffId);
        Staff staff = staffRepository.findByIdOptional(staffId)
                .orElseThrow(() -> new ResourceNotFoundException("Staff", "staffId", staffId));
        return StaffDetailResponse.from(staff);
    }

    /**
     * Create a new staff member along with their user and contact details.
     * All IDs (contact_detail_id, user_id, staff_id) are generated by the database.
     */
    @Transactional
    public StaffDetailResponse createStaff(CreateStaffRequest request) {
        LOG.infof("Creating new staff member: %s %s", request.getFirstName(), request.getLastName());

        // Check email is not already registered
        if (contactDetailRepository.findByPrimaryEmail(request.getPrimaryEmail()).isPresent()) {
            throw new BusinessValidationException(
                    String.format("A user with email '%s' is already registered", request.getPrimaryEmail()));
        }

        // Validate role exists
        Role role = roleRepository.findByRoleId(request.getRoleId());
        if (role == null) {
            throw new ResourceNotFoundException("Role", "roleId", request.getRoleId());
        }

        // Validate staff type exists
        StaffType staffType = staffTypeRepository.findByIdOptional(request.getStaffTypeId())
                .orElseThrow(() -> new ResourceNotFoundException("StaffType", "staffTypeId", request.getStaffTypeId()));

        // Optionally validate qualification
        Qualification qualification = null;
        if (request.getQualificationId() != null) {
            qualification = qualificationRepository.findByIdOptional(request.getQualificationId())
                    .orElseThrow(() -> new ResourceNotFoundException("Qualification", "qualificationId", request.getQualificationId()));
        }

        // Create ContactDetail — DB generates contact_detail_id
        ContactDetail contactDetail = new ContactDetail();
        contactDetail.setPrimaryEmail(request.getPrimaryEmail());
        contactDetail.setSecondaryEmail(request.getSecondaryEmail());
        contactDetail.setPrimaryPhone(request.getPrimaryPhone());
        contactDetail.setSecondaryPhone(request.getSecondaryPhone());
        contactDetail.setAddressLine1(request.getAddressLine1());
        contactDetail.setAddressLine2(request.getAddressLine2());
        contactDetail.setCity(request.getCity());
        contactDetail.setCountry(request.getCountry());
        contactDetail.setPostcode(request.getPostcode());
        contactDetail.setRecordCreatedBy("SYSTEM");
        contactDetail.setRecordUpdatedBy("SYSTEM");
        contactDetailRepository.persist(contactDetail);

        // Create User — DB generates user_id
        User user = new User();
        user.setFirstName(request.getFirstName());
        user.setMiddleName(request.getMiddleName());
        user.setLastName(request.getLastName());
        user.setDob(request.getDob());
        user.setRoleId(role);
        user.setContactDetail(contactDetail);

        // Generate default password and hash it
        String defaultPassword = "Welcome@123";
        user.setPassword(BCrypt.hashpw(defaultPassword, BCrypt.gensalt(10)));

        user.setIsActive(true);
        user.setRecordCreatedBy("SYSTEM");
        user.setRecordUpdatedBy("SYSTEM");
        userRepository.persist(user);

        // Create Staff — DB generates staff_id
        Staff staff = new Staff();
        staff.setUser(user);
        staff.setStaffType(staffType);
        staff.setQualification(qualification);
        staff.setWeeklyHoursCap(request.getWeeklyHoursCap());
        staff.setPreferredShiftTimes(request.getPreferredShiftTimes());
        staff.setIsActive(request.getIsActive() != null ? request.getIsActive() : true);
        staff.setRecordCreatedBy("SYSTEM");
        staff.setRecordUpdatedBy("SYSTEM");
        staffRepository.persist(staff);

        LOG.infof("Staff created successfully — staff_id assigned by DB");
        return StaffDetailResponse.from(staff);
    }

    /**
     * Update an existing staff member
     */
    @Transactional
    public StaffDetailResponse updateStaff(Long staffId, UpdateStaffRequest request, String updatedBy) {
        LOG.infof("Updating staff with ID: %d", staffId);

        Staff staff = staffRepository.findByIdOptional(staffId)
                .orElseThrow(() -> new ResourceNotFoundException("Staff", "staffId", staffId));

        String auditUser = (updatedBy != null && !updatedBy.isEmpty()) ? updatedBy : "SYSTEM";

        // Update user details if provided
        User user = staff.getUser();
        if (user != null) {
            if (request.getFirstName() != null) {
                user.setFirstName(request.getFirstName());
            }
            if (request.getMiddleName() != null) {
                user.setMiddleName(request.getMiddleName());
            }
            if (request.getLastName() != null) {
                user.setLastName(request.getLastName());
            }
            if (request.getDob() != null) {
                user.setDob(request.getDob());
            }
            if (request.getRoleId() != null) {
                Role role = roleRepository.findByRoleId(request.getRoleId());
                if (role == null) {
                    throw new ResourceNotFoundException("Role", "roleId", request.getRoleId());
                }
                user.setRoleId(role);
            }
            user.setRecordUpdatedBy(auditUser);

            // Update contact details if provided
            ContactDetail contactDetail = user.getContactDetail();
            if (contactDetail != null) {
                if (request.getPrimaryEmail() != null) {
                    contactDetail.setPrimaryEmail(request.getPrimaryEmail());
                }
                if (request.getSecondaryEmail() != null) {
                    contactDetail.setSecondaryEmail(request.getSecondaryEmail());
                }
                if (request.getPrimaryPhone() != null) {
                    contactDetail.setPrimaryPhone(request.getPrimaryPhone());
                }
                if (request.getSecondaryPhone() != null) {
                    contactDetail.setSecondaryPhone(request.getSecondaryPhone());
                }
                if (request.getAddressLine1() != null) {
                    contactDetail.setAddressLine1(request.getAddressLine1());
                }
                if (request.getAddressLine2() != null) {
                    contactDetail.setAddressLine2(request.getAddressLine2());
                }
                if (request.getCity() != null) {
                    contactDetail.setCity(request.getCity());
                }
                if (request.getCountry() != null) {
                    contactDetail.setCountry(request.getCountry());
                }
                if (request.getPostcode() != null) {
                    contactDetail.setPostcode(request.getPostcode());
                }
                contactDetail.setRecordUpdatedBy(auditUser);
            }
        }

        // Update staff type if provided
        if (request.getStaffTypeId() != null) {
            StaffType staffType = staffTypeRepository.findByIdOptional(request.getStaffTypeId())
                    .orElseThrow(() -> new ResourceNotFoundException("StaffType", "staffTypeId", request.getStaffTypeId()));
            staff.setStaffType(staffType);
        }

        // Update qualification if provided
        if (request.getQualificationId() != null) {
            Qualification qualification = qualificationRepository.findByIdOptional(request.getQualificationId())
                    .orElseThrow(() -> new ResourceNotFoundException("Qualification", "qualificationId", request.getQualificationId()));
            staff.setQualification(qualification);
        }

        // Update weekly hours cap if provided
        if (request.getWeeklyHoursCap() != null) {
            staff.setWeeklyHoursCap(request.getWeeklyHoursCap());
        }

        // Update preferred shift times if provided
        if (request.getPreferredShiftTimes() != null) {
            staff.setPreferredShiftTimes(request.getPreferredShiftTimes());
        }

        // Update active status if provided
        if (request.getIsActive() != null) {
            staff.setIsActive(request.getIsActive());
        }

        staff.setRecordUpdatedBy(auditUser);

        LOG.infof("Staff updated successfully with ID: %d", staff.getStaffId());
        return StaffDetailResponse.from(staff);
    }

    /**
     * Delete (deactivate) a staff member by setting isActive to false
     * This is a soft delete - the record remains in the database
     */
    @Transactional
    public void deleteStaff(Long staffId, String deletedBy) {
        LOG.infof("Deactivating staff with ID: %d", staffId);

        Staff staff = staffRepository.findByIdOptional(staffId)
                .orElseThrow(() -> new ResourceNotFoundException("Staff", "staffId", staffId));

        // Soft delete - set isActive to false
        staff.setIsActive(false);

        // Update audit fields
        String auditUser = (deletedBy != null && !deletedBy.isEmpty()) ? deletedBy : "SYSTEM";
        staff.setRecordUpdatedBy(auditUser);

        LOG.infof("Staff deactivated successfully with ID: %d", staffId);
    }
}
